[package]
name = "proto"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic.workspace = true
prost = "0.14"
shared = { path = "../shared" }
[build-dependencies]
tonic-build = { git = "https://github.com/hyperium/tonic" }
